In [1]:
import pandas as pd

In [2]:
raw_df = pd.read_csv("../raw_data/bank-full.csv", delimiter=";")
raw_df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [67]:
raw_df[raw_df['y'] == "yes"].poutcome.value_counts(normalize=True)

poutcome
unknown    0.640197
success    0.184912
failure    0.116846
other      0.058045
Name: proportion, dtype: float64

In [68]:
raw_df[raw_df['y'] == "no"].education.value_counts(normalize=True)

education
secondary    0.519814
tertiary     0.283177
primary      0.156806
unknown      0.040203
Name: proportion, dtype: float64

In [87]:
(raw_df.education.value_counts())

education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [71]:
clean_df = raw_df[["age", "balance", "contact", "duration", "job", "marital", "month", "previous", "y"]].copy()
clean_df.sample(10)

,age,balance,contact,duration,job,marital,month,previous,y
35195,35,883,cellular,333,technician,married,may,1,no
7918,39,157,unknown,99,blue-collar,married,may,0,no
28093,26,4130,cellular,104,technician,single,jan,0,no
33340,36,1925,cellular,904,blue-collar,married,apr,0,yes
5377,52,-209,unknown,161,admin.,divorced,may,0,no
27221,35,0,telephone,26,entrepreneur,married,nov,0,no
8200,36,0,unknown,87,entrepreneur,married,jun,0,no
40431,27,565,cellular,148,admin.,married,jul,0,no
33719,78,8556,telephone,137,retired,married,apr,0,yes
33791,67,3377,telephone,77,retired,single,apr,0,no

In [86]:
clean_df.to_csv("banking-simplified.csv", index=False)