In [1]:
import pandas as pd

In [2]:
raw_df = pd.read_csv("../raw_data/bank-full.csv", delimiter=";")
raw_df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [67]:
raw_df[raw_df['y'] == "yes"].poutcome.value_counts(normalize=True)

poutcome
unknown    0.640197
success    0.184912
failure    0.116846
other      0.058045
Name: proportion, dtype: float64

In [68]:
raw_df[raw_df['y'] == "no"].education.value_counts(normalize=True)

education
secondary    0.519814
tertiary     0.283177
primary      0.156806
unknown      0.040203
Name: proportion, dtype: float64

In [70]:
(raw_df.previous.describe())

count    45211.000000
mean         0.580323
std          2.303441
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        275.000000
Name: previous, dtype: float64

In [59]:
clean_df = raw_df[["age", "balance", "duration", "job", "month","contact", "y"]].copy()
clean_df.sample(10)

       age  balance  duration          job month    contact    y
30157   50     -111        19  blue-collar   feb   cellular   no
26121   50     4666        11   management   nov   cellular   no
4041    48       54       293   management   may    unknown   no
32418   41     -692       370  blue-collar   apr   cellular   no
3101    30     1480       360  blue-collar   may    unknown   no
4200    31      754      1022  blue-collar   may    unknown  yes
39489   31      117        77       admin.   may   cellular   no
14349   33        0       305  blue-collar   jul  telephone   no
35355   37      815        77   management   may   cellular   no
25892   30     2074        98       admin.   nov   cellular   no